apiVersion: v1
kind: Pod
metadata:
  name: mypod2
  labels:
    mycka: round-robin
spec:
  containers:
  - name: mycontainer
    image: openshift/hello-openshift
    ports:
    - containerPort: 8080

